---
secrets:
  zulip__postgres_password:
    environment: "ZULIP__POSTGRES_PASSWORD"
  zulip__memcached_password:
    environment: "ZULIP__MEMCACHED_PASSWORD"
  zulip__rabbitmq_password:
    environment: "ZULIP__RABBITMQ_PASSWORD"
  zulip__redis_password:
    environment: "ZULIP__REDIS_PASSWORD"
  zulip__secret_key:
    environment: "ZULIP__SECRET_KEY"
  zulip__email_password:
    environment: "ZULIP__EMAIL_PASSWORD"

services:
  zulip:
    build:
      context: .
      args:
        ZULIP_GIT_URL: https://github.com/zulip/zulip.git
        ZULIP_GIT_REF: "11.5"
    ports:
      # Using 9080/9443 to avoid conflict with Huly on port 80
      - name: http
        target: 80
        published: 9080
        app_protocol: http
      - name: https
        target: 443
        published: 9443
        app_protocol: https
    volumes:
      # Custom nginx config for Merview CORS (runtime mount)
      - ./custom_nginx_config/zulip-include/app:/etc/nginx/zulip-include/app:ro
    environment:
      # Domain configuration
      SETTING_EXTERNAL_HOST: "chat.dollhousemcp.com"
      SETTING_ZULIP_ADMINISTRATOR: "${ZULIP_ADMINISTRATOR}"

      # Cloudflare handles SSL - HTTP-only is now the default, no DISABLE_HTTPS needed
      # Trust Cloudflare reverse proxy IPs + Docker gateway
      LOADBALANCER_IPS: "172.19.0.1,173.245.48.0/20,103.21.244.0/22,103.22.200.0/22,103.31.4.0/22,141.101.64.0/18,108.162.192.0/18,190.93.240.0/20,188.114.96.0/20,197.234.240.0/22,198.41.128.0/17,162.158.0.0/15,104.16.0.0/13,104.24.0.0/14,172.64.0.0/13,131.0.72.0/22"

      # Email configuration via Resend SMTP
      SETTING_EMAIL_HOST: "smtp.resend.com"
      SETTING_EMAIL_HOST_USER: "resend"
      SETTING_EMAIL_PORT: "465"
      SETTING_EMAIL_USE_SSL: "True"
      SETTING_EMAIL_USE_TLS: "False"
      SETTING_NOREPLY_EMAIL_ADDRESS: "noreply@dollhousemcp.com"
      SETTING_ADD_TOKENS_TO_NOREPLY_ADDRESS: "False"

      # Authentication
      ZULIP_AUTH_BACKENDS: "EmailAuthBackend"

      # Mobile push notifications
      SETTING_ZULIP_SERVICE_PUSH_NOTIFICATIONS: "True"
    secrets:
      []

  # === Bots ===

  formatter-bot:
    build: ./bots/formatter
    restart: unless-stopped
    environment:
      ZULIP_SITE: "https://chat.dollhousemcp.com"
      ZULIP_EMAIL: "${FORMATTER_BOT_EMAIL}"
      ZULIP_API_KEY: "${FORMATTER_BOT_API_KEY}"
    depends_on:
      - zulip

  email-notifier:
    build: ./bots/email-notifier
    restart: unless-stopped
    environment:
      EMAIL_BOT_API_KEY: "${EMAIL_BOT_API_KEY}"
    volumes:
      - ./bots/email-notifier/config.yaml:/app/config.yaml:ro
      - ./bots/email-notifier/credentials.json:/app/credentials.json:ro
      - ./bots/email-notifier/token.json:/app/token.json:rw
    depends_on:
      - zulip

  mcp-news-bot:
    build: ./bots/mcp-news-bot
    restart: unless-stopped
    environment:
      FORMATTER_BOT_API_KEY: "${FORMATTER_BOT_API_KEY}"
    volumes:
      - ./bots/mcp-news-bot/seen_items.json:/app/seen_items.json:rw
    depends_on:
      - zulip

  ai-news-bot:
    build: ./bots/ai-news-bot
    restart: unless-stopped
    environment:
      FORMATTER_BOT_API_KEY: "${FORMATTER_BOT_API_KEY}"
    volumes:
      - ./bots/ai-news-bot/seen_items.json:/app/seen_items.json:rw
    depends_on:
      - zulip

  merview-news-bot:
    build: ./bots/merview-news-bot
    restart: unless-stopped
    environment:
      MERVIEW_NEWS_BOT_API_KEY: "${MERVIEW_NEWS_BOT_API_KEY}"
    volumes:
      - ./bots/merview-news-bot/seen_items.json:/app/seen_items.json:rw

  merview-github-bot:
    build: ./bots/merview-github-bot
    restart: unless-stopped
    environment:
      MERVIEW_GITHUB_BOT_API_KEY: "${MERVIEW_GITHUB_BOT_API_KEY}"
    volumes:
      - ./bots/merview-github-bot/seen_items.json:/app/seen_items.json:rw

  merview-digest-bot:
    build: ./bots/merview-digest-bot
    restart: unless-stopped
    environment:
      MERVIEW_DIGEST_BOT_API_KEY: "${MERVIEW_DIGEST_BOT_API_KEY}"
      GITHUB_TOKEN: "${GITHUB_TOKEN}"

  claude-skills-bot:
    build: ./bots/claude-skills-bot
    restart: unless-stopped
    environment:
      FORMATTER_BOT_API_KEY: "${FORMATTER_BOT_API_KEY}"
    volumes:
      - ./bots/claude-skills-bot/seen_items.json:/app/seen_items.json:rw
    depends_on:
      - zulip

  discord-merview-bot:
    build: ./bots/discord-merview-bot
    restart: unless-stopped
    environment:
      DISCORD_BOT_TOKEN: "${DISCORD_MERVIEW_BOT_TOKEN}"
      MERVIEW_URL: "https://merview.com/"

  arxiv-news-bot:
    build:
      context: ./bots
      dockerfile: arxiv-news-bot/Dockerfile
    restart: unless-stopped
    environment:
      FORMATTER_BOT_API_KEY: "${FORMATTER_BOT_API_KEY}"
    volumes:
      - ./bots/arxiv-news-bot/seen_items.json:/app/arxiv-news-bot/seen_items.json:rw
    depends_on:
      - zulip

  youtube-news-bot:
    build:
      context: ./bots
      dockerfile: youtube-news-bot/Dockerfile
    restart: unless-stopped
    environment:
      FORMATTER_BOT_API_KEY: "${FORMATTER_BOT_API_KEY}"
      YOUTUBE_API_KEY: "${YOUTUBE_API_KEY}"
    volumes:
      - ./bots/youtube-news-bot/seen_items.json:/app/youtube-news-bot/seen_items.json:rw
    depends_on:
      - zulip

  linkedin-news-bot:
    build:
      context: ./bots
      dockerfile: linkedin-news-bot/Dockerfile
    restart: unless-stopped
    environment:
      FORMATTER_BOT_API_KEY: "${FORMATTER_BOT_API_KEY}"
    volumes:
      - ./bots/linkedin-news-bot/seen_items.json:/app/linkedin-news-bot/seen_items.json:rw
    depends_on:
      - zulip

  twitter-news-bot:
    build:
      context: ./bots
      dockerfile: twitter-news-bot/Dockerfile
    restart: unless-stopped
    environment:
      FORMATTER_BOT_API_KEY: "${FORMATTER_BOT_API_KEY}"
    volumes:
      - ./bots/twitter-news-bot/seen_items.json:/app/twitter-news-bot/seen_items.json:rw
    depends_on:
      - zulip

  bluesky-news-bot:
    build:
      context: ./bots
      dockerfile: bluesky-news-bot/Dockerfile
    restart: unless-stopped
    environment:
      FORMATTER_BOT_API_KEY: "${FORMATTER_BOT_API_KEY}"
      BLUESKY_IDENTIFIER: "${BLUESKY_IDENTIFIER}"
      BLUESKY_APP_PASSWORD: "${BLUESKY_APP_PASSWORD}"
    volumes:
      - ./bots/bluesky-news-bot/seen_items.json:/app/bluesky-news-bot/seen_items.json:rw
    depends_on:
      - zulip

  mastodon-news-bot:
    build:
      context: ./bots
      dockerfile: mastodon-news-bot/Dockerfile
    restart: unless-stopped
    environment:
      FORMATTER_BOT_API_KEY: "${FORMATTER_BOT_API_KEY}"
    volumes:
      - ./bots/mastodon-news-bot/seen_items.json:/app/mastodon-news-bot/seen_items.json:rw
    depends_on:
      - zulip
